// Map definitions. Coordinates are metres, x = east, z = south (north is -z on every minimap).
// The playable square is [-500, 500] on both axes. Every prop/landmark with an `egg` is a discoverable easter egg.

const E = (id, title, text, r = 12) => ({ id, title, text, r });

// Koramangala is built from real OpenStreetMap data; this projects real lat/lon to its game metres.
const KC = [12.9325, 77.6230];
const at = (lat, lon, o = {}) => ({ x: Math.round((lon - KC[1]) * 111320 * Math.cos((KC[0] * Math.PI) / 180)), z: Math.round(-(lat - KC[0]) * 110574), ...o });

export const MAPS = [
  // ------------------------------------------------------------------ KORAMANGALA (real map, night)
  {
    id: 'koramangala', name: 'Koramangala', native: 'ಕೋರಮಂಗಲ', state: 'Bengaluru, Karnataka',
    tagline: 'Real streets. Real pubs. Real Silk Board.',
    blurb: 'Bengaluru\'s startup and pub capital at night, built from real map data: every road, every building footprint and every named shop from Silk Board to Ejipura.',
    osm: 'data/koramangala.json', half: 1850,
    // the night HDRI is exposure-normalised (as bright as day), so it is dimmed hard here
    sky: 'qwantani_night_puresky', exposure: 1.05, env: 0.28, sun: 0.55, fog: 0.0014, fogColor: '#121829', bgI: 0.09, night: true,
    weather: { rain: 0, rainAfter: 300, rainAmount: 0.45 },
    terrain: { kind: 'flat', amp: 2, freq: 1 / 420, base: 6 },
    ground: ['dryGround', 'redDirt', 'rock', 'grassSparse'],
    roads: [], districts: [], landmarks: [],
    places: [
      ['Koramangala 1st Block', 12.9277, 77.6328], ['Koramangala 2nd Block', 12.9244, 77.6242], ['Koramangala 3rd Block', 12.9283, 77.6254],
      ['Koramangala 4th Block', 12.9328, 77.6294], ['Koramangala 5th Block', 12.9348, 77.6190], ['Koramangala 6th Block', 12.9390, 77.6238],
      ['Koramangala 7th Block', 12.9365, 77.6135], ['Koramangala 8th Block', 12.9409, 77.6173], ['ST Bed Layout', 12.9348, 77.6324],
      ['Ejipura', 12.9452, 77.6275], ['Adugodi', 12.9440, 77.6089], ['Madiwala', 12.9238, 77.6176], ['Jakkasandra', 12.9243, 77.6376],
      ['Venkatapura', 12.9226, 77.6345], ['Teacher\'s Colony', 12.9188, 77.6341], ['Maruthi Nagar', 12.9225, 77.6139], ['Tavarekere', 12.9220, 77.6096],
      ['BTM 1st Stage', 12.9190, 77.6113], ['Rajendranagar', 12.9466, 77.6175], ['Sadgunte Palya', 12.9315, 77.6096], ['KHB Colony', 12.9350, 77.6178],
      ['Silk Board Junction', 12.9176, 77.6232, true], ['Sony World Signal', 12.9373, 77.6266, true], ['80 Feet Road', 12.9352, 77.6251, true],
    ],
    props: [
      at(12.9179, 77.6236, { kind: 'jam', len: 70, egg: E('silkboard', 'Silk Board Junction', 'The real one. Estimated waiting time: 2 business days. Some of these cars came in 2014.', 45) }),
      at(12.9373, 77.6266, { kind: 'coder_bike', egg: E('sonyworld', 'Sony World Signal', 'Guy on a bike at Sony World signal, laptop open, fixing a prod bug before the light turns green. Peak Koramangala.') }),
      at(12.9352, 77.6250, { kind: 'stall', sign: ['80 FEET ROAD', 'PUB CAPITAL OF INDIA'], color: '#ff9f1c', egg: E('pubs', 'Pub Capital', 'Koramangala has more microbreweries than working traffic signals. Last order 12:59 AM, sharp. Bouncer is stricter than your manager.') }),
      at(12.9331, 77.6199, { kind: 'stall', sign: ['ದರ್ಶಿನಿ', 'FILTER KAAPI ₹15'], color: '#f4b400', egg: E('darshini', 'Darshini', 'Filter kaapi ₹15, chutney refills unlimited, chairs not invented yet. Stand and eat like a true Bengalurean.') }),
      at(12.9336, 77.6268, { kind: 'pothole', egg: E('pothole', 'The Pothole', 'This pothole has its own Maps listing. 4.2★ — "great depth, lovely ambience".') }),
      at(12.9296, 77.6281, { kind: 'pothole' }), at(12.9398, 77.6256, { kind: 'pothole' }), at(12.9270, 77.6300, { kind: 'pothole' }),
      at(12.9353, 77.6268, { kind: 'billboard', text: ['UBER FOR IDLI', 'Series A · pre-revenue · pre-idli'], neon: '#ff3f8e', egg: E('startup', 'Startup Street', 'Uber for Idli just raised ₹400 crore from a 4th Block café. They have not made a single idli. Valuation: unicorn.') }),
      at(12.9289, 77.6232, { kind: 'billboard', text: ['1BHK FOR RENT', '₹45,000 + 10 months deposit'], neon: '#2de2e6', egg: E('rent', '1BHK for Rent', 'Rent: ₹45,000. Deposit: 10 months. Landlord interview: 3 rounds, including a coding test.') }),
      at(12.9407, 77.6241, { kind: 'billboard', text: ['WE ARE HIRING', '15 yrs exp in a 2-yr-old framework'], neon: '#b4ff39', egg: E('hiring', 'Now Hiring', 'Requirements: 15 years of experience in a framework released last year. Salary: exposure and free kombucha.') }),
      at(12.9371, 77.6240, { kind: 'banner', text: ['ಸ್ವಲ್ಪ ಅಡ್ಜಸ್ಟ್ ಮಾಡಿ', 'SWALPA ADJUST MAADI'], egg: E('adjust', 'Swalpa Adjust Maadi', 'The city\'s official motto. Applies to buses, autos, relationships and blue zones.') }),
      at(12.9316, 77.6190, { kind: 'auto_sign', text: ['METER? ILLA SAAR', 'One and half only'], egg: E('auto', 'Auto Anna', '"Meter illa saar, one and half. Koramangala to Indiranagar? Traffic saar. Two."') }),
      at(12.9373, 77.6216, { kind: 'sign', text: ['INDOOR STADIUM', 'Badminton at 6 AM · networking at 7'], egg: E('stadium', 'Koramangala Indoor Stadium', 'Half the players here are playing badminton. The other half are pitching their startup between points.') }),
      at(12.9336, 77.6180, { kind: 'sign', text: ['BDA COMPLEX', 'Rent agreements & patience expire here'], egg: E('bda', 'BDA Complex', 'Come for the rent agreement, stay for the queue. Leave with a new appreciation for Aadhaar.') }),
      at(12.9346, 77.6116, { kind: 'sign', text: ['THE MALL', 'Every weekend · every Bengalurean'], egg: E('mall', 'The Mall', 'Weekend plan: go to the mall, sit in the AC, get a filter coffee, go home. Repeat for 52 weeks.') }),
      at(12.9349, 77.6302, { kind: 'stall', sign: ['MOMOS · 2 AM', 'Koramangala after-party HQ'], color: '#d32f2f', egg: E('momos', 'The 2 AM Momo Stall', 'The pubs close at 1. This stall opens at 1:01. It has seen more startup ideas than any accelerator.') }),
      at(12.9293, 77.6197, { kind: 'sign', text: ['ST. JOHN\'S', 'Your parents still want you to be a doctor'], egg: E('stjohns', 'St. John\'s', 'Every Koramangala founder\'s parents drive past here and sigh: "You could have been a doctor."') }),
      at(12.9231, 77.6181, { kind: 'stall', sign: ['MADIWALA MARKET', 'Fresh, loud, since forever'], color: '#43a047', egg: E('madiwala', 'Madiwala Market', 'Vegetables, flowers, fish and the best bargaining practice in the city. Say "last price?" three times.') }),
      at(12.9447, 77.6281, { kind: 'sign', text: ['EJIPURA FLYOVER', 'Under construction since 2017'], egg: E('ejipura', 'Ejipura Flyover', 'Started in 2017. Expected completion: "next year". Every year. It is a national treasure now.') }),
      at(12.9362, 77.6143, { kind: 'sign', text: ['BENGALURU WEATHER', '24°C forever · rain 4:00 PM sharp'], egg: E('weather', 'The Weather Board', 'Bengaluru weather: 24°C forever. Rain at 4 PM, sharp. It\'s in the SLA.') }),
    ],
    billboards: [
      { text: ['UBER FOR IDLI', 'Series A · pre-revenue'], neon: '#ff3f8e' }, { text: ['WFH? WFC!', 'Work from café · Koramangala'], neon: '#2de2e6' },
      { text: ['SILK BOARD ETA', 'See you next quarter'], neon: '#ffb000' }, { text: ['DOSA 2.0', 'Now on the blockchain'], neon: '#b4ff39' },
      { text: ['FILTER KAAPI ₹15', 'Better than your ₹300 latte'], neon: '#ffb000' }, { text: ['PEAK BENGALURU', 'Pitching at a red light'], neon: '#8e44ad' },
      { text: ['METRO SOON™', 'Since 2012'], neon: '#2de2e6' }, { text: ['RAIN AT 4 PM', 'Carry the umbrella, macha'], neon: '#4aa3ff' },
      { text: ['1BHK ₹45,000', '+10 months deposit'], neon: '#ff3f8e' }, { text: ['SWALPA ADJUST MAADI', 'Namma Bengaluru'], neon: '#ffb000' },
    ],
    trees: { kinds: ['raintree', 'gulmohar', 'coconut', 'raintree'], count: 0 },
    vehicles: ['auto', 'auto', 'auto', 'bike', 'bike', 'jeep'], vehicleCount: 42,
    signs: ['ಶ್ರೀ ಗಣೇಶ ಬೇಕರಿ', 'IYENGAR BAKERY', 'NAMMA MOBILES', 'KAAPI KATTE', 'ಹೋಟೆಲ್ ಉಪಹಾರ', 'IDLI FACTORY', '24x7 MEDICALS', 'CO-WORK CAFE', 'ಬೆಣ್ಣೆ ದೋಸೆ', 'PG FOR GENTS', 'MICROBREWERY', 'MOMOS POINT', 'TECH REPAIRS'],
    neon: ['#2de2e6', '#ff3f8e', '#ffb000', '#b4ff39'],
    walls: ['#e8dcc6', '#d9c2a3', '#c9d6c2', '#e6e2d8', '#e4b77c', '#b8c4cc', '#f0e2b6', '#d7a78a', '#f2f2ee', '#cfe0e8'],
    roofs: ['#9a4a33', '#7d3b2a'],
    mechanics: { rainAt4pm: true, potholes: true },
    food: { id: 'filterkaapi', name: 'Filter Kaapi', kind: 'boost', amount: 45, time: 3, desc: 'Degree coffee in a steel tumbler. +45 boost.' },
    zoneMsgs: ['Zone barthide, swalpa adjust maadi!', 'The zone is coming — adjust maadi!'],
    killVerbs: ['adjusted', 'sent to Silk Board', 'ghosted', 'laid off'],
    win: 'WINNER WINNER MASALA DOSA DINNER',
    plane: 'Namma Airways KA-01',
    bots: ['SilkBoardSurvivor', 'AdjustMaadi', 'FilterKaapiFiend', 'KoramangalaKing', 'SonyWorldSignal', '80FeetRoad', 'StandupMeetingGuy', 'BenneDosaBoss', 'ForumMallRat', 'Rain4PM', 'AutoAnna', 'EjipuraFlyover', 'MetroSoonTM', 'PGforGents', 'TenXEngineer', 'StBedSniper', 'MadiwalaMarket', 'MomosAt2AM', 'StartupSaurabh', 'SeriesAFunded', 'PubCrawler', 'BTMBoss', 'WFCWarrior', 'KaapiKatte'],
    tips: ['This is the real Koramangala: the roads, buildings and shops come from OpenStreetMap.', 'Shop doors have loot. Restaurants and cafés often drop Filter Kaapi.', 'The Silk Board flyover is raised — high ground over the jam.', 'Big map: grab an auto-rickshaw early.', 'Rain arrives at "4 PM", a few minutes into the match.'],
  },


  // ------------------------------------------------------------------ BENGALURU
  {
    id: 'bangalore', name: 'Bengaluru Classic', native: 'ಬೆಂಗಳೂರು', state: 'Karnataka',
    tagline: 'Silicon Valley of India — traffic edition',
    blurb: 'Tech parks, filter kaapi and a junction nobody has ever left. Rain arrives at 4 PM sharp.',
    sky: 'kloofendal_48d_partly_cloudy_puresky', exposure: 0.95, env: 0.9, sun: 3.2, fog: 0.0016,
    weather: { rain: 0, rainAfter: 150, rainAmount: 0.7 },
    terrain: { kind: 'flat', amp: 7, freq: 1 / 260, base: 6 },
    lakes: [{ x: 330, z: 330, r: 80, foam: true }, { x: 150, z: -250, r: 42 }],
    ground: ['grass', 'redDirt', 'rock', 'grassSparse'],
    roads: [
      { pts: [[-500, 0], [500, 0]], w: 16 },
      { pts: [[-500, 250], [-200, 245], [100, 205], [240, 180], [500, 160]], w: 14 },
      { pts: [[-150, -500], [-150, 500]], w: 13 },
      { pts: [[240, 180], [330, -150], [380, -500]], w: 14 },
      { pts: [[240, 180], [280, 500]], w: 12 },
      { pts: [[-500, -380], [-150, -380], [100, -420], [500, -430]], w: 10 },
    ],
    districts: [
      { x: 20, z: -85, w: 270, d: 130, style: 'urban', block: 50 },
      { x: 20, z: 75, w: 270, d: 110, style: 'shops', block: 42 },
      { x: -330, z: -200, w: 250, d: 230, style: 'oldhouse', block: 46 },
      { x: 30, z: 360, w: 300, d: 230, style: 'urban', block: 48 },
      { x: 360, z: -300, w: 210, d: 220, style: 'techpark', block: 70 },
      { x: -330, z: 330, w: 250, d: 230, style: 'urban', block: 50 },
      { x: -360, z: 100, w: 220, d: 130, style: 'industrial', block: 64 },
    ],
    parks: [{ x: -40, z: -330, r: 75 }],
    landmarks: [
      { kind: 'vidhana_soudha', x: -40, z: -225, egg: E('vidhana', 'Vidhana Soudha', '"Government work is God\'s work" is carved on the front. The file you applied for in 2009 is still in there.', 45) },
      { kind: 'metro', pts: [[-480, 8], [480, 8]], color: '#8e44ad', name: 'NAMMA METRO', egg: E('metro', 'Namma Metro', 'Phase 2 opening soon. It\'s been "soon" since 2012.', 14), eggAt: [100, 8] },
      { kind: 'flyover_jam', x: 240, z: 180, len: 150, dir: 'x', egg: E('silkboard', 'Silk Board Junction', 'Welcome to Silk Board. Estimated waiting time: 2 business days. Some of these cars came in 2014.', 40) },
    ],
    props: [
      { kind: 'stall', x: -120, z: 16, rot: 2, sign: ['ದರ್ಶಿನಿ', 'FILTER KAAPI ₹15'], color: '#f4b400', egg: E('darshini', 'Darshini', 'Filter kaapi ₹15, chutney refills unlimited, chairs: not invented yet. Stand and eat like a true Bengalurean.') },
      { kind: 'pothole', x: 60, z: 0, egg: E('pothole', 'The Pothole', 'This pothole has its own Maps listing. 4.2★ — "great depth, lovely ambience".') },
      { kind: 'pothole', x: -260, z: 248 }, { kind: 'pothole', x: -150, z: 120 }, { kind: 'pothole', x: 300, z: 60 },
      { kind: 'coder_bike', x: -142, z: 30, rot: 0, egg: E('coder', 'Peak Bengaluru', 'Guy on a bike at a red light, laptop open, fixing a prod bug. Peak Bengaluru moment unlocked.') },
      { kind: 'billboard', x: 180, z: -30, rot: 2, text: ['UBER FOR IDLI', 'Series A funded · pre-revenue · pre-idli'], neon: '#ff3f8e', egg: E('startup', 'Startup Hoarding', 'Uber for Idli just raised ₹400 crore. They have not made a single idli. Valuation: unicorn.') },
      { kind: 'billboard', x: -30, z: 150, rot: 0, text: ['1BHK FOR RENT', '₹45,000 + 10 months deposit'], neon: '#2de2e6', egg: E('rent', '1BHK for Rent', 'Rent: ₹45,000. Deposit: 10 months. Landlord interview: 3 rounds, including a coding test.') },
      { kind: 'banner', x: -150, z: -60, rot: 1, text: ['ಸ್ವಲ್ಪ ಅಡ್ಜಸ್ಟ್ ಮಾಡಿ', 'SWALPA ADJUST MAADI'], egg: E('adjust', 'Swalpa Adjust Maadi', 'The city\'s official motto. Applies to buses, autos, relationships and blue zones.') },
      { kind: 'auto_sign', x: 160, z: 20, rot: 1, text: ['METER? ILLA SAAR', 'One and half only'], egg: E('auto', 'Auto Anna', '"Meter illa saar, one and half. Return empty coming, you understand no?"') },
      { kind: 'sign', x: -80, z: -300, rot: 0, text: ['BENGALURU WEATHER', '24°C forever · Rain 4:00 PM sharp'], egg: E('weather', 'The Weather Board', 'Bengaluru weather: 24°C forever. Rain at 4 PM, sharp. It\'s in the SLA.') },
      { kind: 'foam', x: 330, z: 330, egg: E('bellandur', 'Bellandur Lake', 'Complimentary bubble bath. Please do not light a cigarette near the foam.', 60) },
      { kind: 'stall', x: 100, z: 90, rot: 0, sign: ['BENNE DOSA', 'Butter · more butter'], color: '#ffd166', egg: E('benne', 'Benne Dosa', 'One benne dosa contains the daily butter allowance of a small village. Worth it.') },
      { kind: 'billboard', x: 330, z: -120, rot: 3, text: ['WE ARE HIRING', '10x rockstar ninja · 0 years exp · 15 yrs React'], neon: '#b4ff39', egg: E('hiring', 'Now Hiring', 'Requirements: 15 years of experience in a framework released last year. Salary: exposure.') },
      { kind: 'stall', x: -250, z: -10, rot: 2, sign: ['BEER CAPITAL', 'Happy hours: 11 AM – 11 PM'], color: '#ff9f1c', egg: E('pub', 'Pub Capital', 'Bengaluru has more microbreweries than working traffic signals.') },
      { kind: 'jam', x: -40, z: 250, len: 70, dir: 'x', egg: E('orr', 'Outer Ring Road', 'ORR at 6 PM. Walking is faster. Crawling is faster. Loot respawns faster.') },
    ],
    trees: { kinds: ['raintree', 'gulmohar', 'coconut', 'raintree'], count: 1100 },
    vehicles: ['auto', 'auto', 'auto', 'bike', 'bike', 'jeep'], vehicleCount: 16,
    signs: ['ಶ್ರೀ ಗಣೇಶ ಬೇಕರಿ', 'IYENGAR BAKERY', 'NAMMA MOBILES', 'KAAPI KATTE', 'ಹೋಟೆಲ್ ಉಪಹಾರ', 'IDLI FACTORY', '24x7 MEDICALS', 'SILK SAREES', 'ANNA TIFFINS', 'TECH SUPPORT HUB', 'CO-WORK CAFE', 'ಬೆಣ್ಣೆ ದೋಸೆ', 'GADGET WORLD', 'PG FOR GENTS', 'RAVA IDLI CORNER'],
    neon: ['#2de2e6', '#ff3f8e', '#ffb000', '#8e44ad'],
    walls: ['#e8dcc6', '#d9c2a3', '#c9d6c2', '#e6e2d8', '#e4b77c', '#b8c4cc', '#f0e2b6', '#d7a78a'],
    roofs: ['#9a4a33', '#7d3b2a'],
    mechanics: { rainAt4pm: true, potholes: true },
    food: { id: 'filterkaapi', name: 'Filter Kaapi', kind: 'boost', amount: 45, time: 3, desc: 'Degree coffee in a steel tumbler. +45 boost.' },
    zoneMsgs: ['Zone barthide, swalpa adjust maadi!', 'The zone is coming — adjust maadi!'],
    killVerbs: ['adjusted', 'sent to Silk Board', 'ghosted', 'laid off'],
    win: 'WINNER WINNER MASALA DOSA DINNER',
    plane: 'Namma Airways KA-01',
    bots: ['SilkBoardSurvivor', 'AdjustMaadi', 'FilterKaapiFiend', 'KoramangalaKing', 'HSR_Hustler', 'WhitefieldWarrior', 'StandupMeetingGuy', 'BenneDosaBoss', 'IndiranagarIndie', 'Rain4PM', 'AutoAnna', 'ORR_Crawler', 'MetroSoonTM', 'PGforGents', 'TenXEngineer', 'JayanagarJedi', 'MysoreMasala', 'BellandurBubbles', 'CubbonJogger', 'SeriesAFunded'],
    tips: ['Rain starts at "4 PM" — a few minutes into the match. Footsteps get quieter.', 'Potholes slow down vehicles. Bengaluru drivers call it "natural speed breaker".', 'Silk Board junction: vehicles move at walking pace. Walk.', 'Filter Kaapi gives +45 boost. Tumbler not included.', 'The metro viaduct gives high ground across the whole map.'],
  },

  // ------------------------------------------------------------------ KOCHI
  {
    id: 'kochi', name: 'Kochi', native: 'കൊച്ചി', state: 'Kerala',
    tagline: 'Queen of the Arabian Sea',
    blurb: 'Chinese fishing nets, backwaters, porotta-beef and a monsoon that never really leaves.',
    sky: 'overcast_soil_puresky', exposure: 1.05, env: 1.0, sun: 1.6, fog: 0.0022,
    weather: { rain: 0.55 },
    terrain: { kind: 'coastal', amp: 3, freq: 1 / 220, base: 4 },
    sea: { axis: 'x', sign: -1, at: 360 },
    rivers: [{ pts: [[-200, -520], [-215, -200], [-190, 60], [-230, 300], [-210, 520]], w: 34 }],
    ground: ['grass', 'redDirt', 'rock', 'sand'],
    roads: [
      { pts: [[-150, -500], [-150, 500]], w: 12 },
      { pts: [[100, -500], [100, 500]], w: 16 },
      { pts: [[-330, -60], [-160, -80], [100, -80], [500, -60]], w: 12, bridge: true },
      { pts: [[-150, 220], [500, 220]], w: 12 },
      { pts: [[-340, -400], [-270, 0], [-300, 400]], w: 9 },
      { pts: [[100, -330], [500, -330]], w: 12 },
    ],
    districts: [
      { x: -290, z: -60, w: 90, d: 560, style: 'colonial', block: 40 },
      { x: 10, z: 60, w: 280, d: 200, style: 'shops', block: 42 },
      { x: 280, z: 60, w: 220, d: 200, style: 'urban', block: 48 },
      { x: 330, z: -300, w: 260, d: 240, style: 'techpark', block: 70 },
      { x: 20, z: -300, w: 250, d: 240, style: 'kerala', block: 52 },
      { x: 150, z: 380, w: 520, d: 200, style: 'kerala', block: 54 },
    ],
    landmarks: [
      { kind: 'fishing_nets', x: -340, z: -200, n: 5, dir: 'z', egg: E('cheenavala', 'Cheena Vala', 'Chinese fishing nets: the original Chinese app India never banned.', 40) },
      { kind: 'metro', pts: [[100, -480], [100, 480]], color: '#00a3b4', name: 'KOCHI METRO', offset: 10, egg: E('kmetro', 'Kochi Metro', 'So clean you feel guilty breathing inside it.', 14), eggAt: [110, 0] },
      { kind: 'mall', x: 300, z: 220, name: 'MEGA MALL', egg: E('mall', 'The Mall', 'Weekend plan: go to the mall, sit in the AC, eat, go home. Repeat for 52 weeks.', 40) },
      { kind: 'houseboat', x: -205, z: 150, rot: 1, egg: E('houseboat', 'Kettuvallam', 'Houseboat: WiFi weak, vibes strong, karimeen fry excellent.', 20) },
      { kind: 'church', x: -300, z: -300, color: '#f2efe6', spires: 1, egg: E('stfrancis', 'Old Church, Fort Kochi', 'Five centuries old. Has seen the Portuguese, the Dutch, the British and now you, with a frying pan.', 22) },
      { kind: 'rainbow_bridge', x: -170, z: 20, egg: E('marinedrive', 'Marine Drive', 'Marine Drive walkway: couples, ice cream, sunset, and one uncle doing brisk walking at maximum speed.', 25) },
    ],
    props: [
      { kind: 'stall', x: -140, z: -95, rot: 2, sign: ['ചായക്കട', 'CHAYA ₹12 · PARIPPU VADA'], color: '#ff7043', egg: E('chayakada', 'Chaya Kada', 'One chaya, one parippu vada and a two-hour political debate. Total: ₹20.') },
      { kind: 'stall', x: 80, z: 150, rot: 1, sign: ['POROTTA + BEEF FRY', 'Kerala\'s national anthem'], color: '#c0392b', egg: E('porotta', 'Porotta & Beef', 'Porotta + beef fry. Doctors hate it. Everyone else loves it.') },
      { kind: 'stall', x: 180, z: -150, rot: 3, sign: ['കള്ള് ഷാപ്പ്', 'FRESH TODDY · FRESHER GOSSIP'], color: '#16a085', egg: E('toddy', 'Kallu Shaap', 'Toddy shop menu: kappa, fish curry, gossip. The gossip is the freshest item.') },
      { kind: 'banner', x: 100, z: 120, rot: 1, text: ['MANJAPPADA', 'We lose. We cry. We come back.'], bg: '#ffd400', fg: '#0b2d6b', egg: E('manjappada', 'Yellow Army', 'Manjappada: the loudest fans in Indian football. Losing is optional, singing is mandatory.') },
      { kind: 'billboard', x: -160, z: 180, rot: 1, text: ['DASHAMOOLAM DAMU', 'Fans Association · Kochi Unit'], neon: '#ffb000', egg: E('damu', 'Damu Fans Assn.', 'Every Malayali meme page has one admin and one Damu template.') },
      { kind: 'sign', x: 60, z: -260, rot: 0, text: ['COCONUT ZONE', 'Helmet Lv.3 recommended'], egg: E('coconut', 'Coconut Zone', 'Falling coconuts do more damage than a Kar98k. Stand under palms at your own risk.') },
      { kind: 'gulf_house', x: 230, z: 420, egg: E('gulf', 'Gulf House', 'Built with 30 years of Dubai overtime. Gold paint, two cars, nobody living in it.', 20) },
      { kind: 'billboard', x: 250, z: -60, rot: 2, text: ['ADIPOLI', 'അടിപൊളി'], neon: '#2de2e6', egg: E('adipoli', 'Adipoli!', 'Adipoli = awesome. Use it for food, films, headshots.') },
      { kind: 'sign', x: -120, z: 300, rot: 1, text: ['MONSOON', 'The only season · umbrella mandatory'], egg: E('monsoon', 'Monsoon', 'Kochi has two seasons: monsoon and waiting for the monsoon.') },
      { kind: 'boat', x: -210, z: -250, egg: E('watermetro', 'Water Metro', 'Water Metro: the only commute in India with a view and a breeze.') },
    ],
    trees: { kinds: ['coconut', 'coconut', 'coconut', 'raintree', 'banana'], count: 1500 },
    vehicles: ['auto', 'auto', 'bike', 'jeep', 'boat', 'boat'], vehicleCount: 14,
    signs: ['കേരള ഹോട്ടൽ', 'GOLD HOUSE', 'MALABAR TEXTILES', 'അമ്മ മെസ്സ്', 'SPICE EXPORTS', 'COCONUT OIL DEPOT', 'CHIPS & HALWA', 'ബേക്കറി', 'MOBILE WORLD', 'SHAWARMA KING', 'TEA & SNACKS', 'ARABIAN GRILL', 'AYURVEDA SPA'],
    neon: ['#2de2e6', '#ff3f8e', '#9bff6a', '#ffb000'],
    walls: ['#f3e6c8', '#bfe0d0', '#f0c9a0', '#d9e8f0', '#f2d7e0', '#e8e0a8', '#c5d8b5', '#f6f0e4'],
    roofs: ['#a8472f', '#8f3a28', '#b3553a'],
    mechanics: { coconuts: true },
    food: { id: 'chaya', name: 'Chaya', kind: 'boost', amount: 40, time: 3, desc: 'Strong tea, pulled from a height. +40 boost.' },
    zoneMsgs: ['Zone varunnu, odikko!', 'The zone is coming — run!'],
    killVerbs: ['sent to Vypin', 'porotta-flipped', 'sent on a houseboat', 'adipoli-ed'],
    win: 'WINNER WINNER POROTTA BEEF DINNER',
    plane: 'Kochi Kappal Air KL-07',
    bots: ['PorottaPredator', 'ChayaAddict', 'KarimeenKing', 'FortKochiPhantom', 'VypinViper', 'MallAC_Enjoyer', 'Manjappada4Life', 'GulfUncle', 'AdipoliAimbot', 'KappaAndMeen', 'MarineDriveWalker', 'Enthuvade', 'KallushaapKid', 'MonsoonMagic', 'CheenaVala', 'BackwaterBoss', 'KeralaCafe', 'CoconutDropper', 'DamuFan', 'Machane'],
    tips: ['Stay away from coconut palms when you hear a rustle.', 'Chaya gives +40 boost. Parippu vada not included.', 'Boats spawn near the backwaters. Fort Kochi is an island.', 'The rain never stops. Use the noise to push.'],
  },

  // ------------------------------------------------------------------ CHENNAI
  {
    id: 'chennai', name: 'Chennai', native: 'சென்னை', state: 'Tamil Nadu',
    tagline: 'Three seasons: hot, hotter, hottest',
    blurb: 'Marina beach, filter coffee, temple gopurams and an afternoon sun that drains your stamina.',
    sky: 'qwantani_noon_puresky', exposure: 0.9, env: 0.9, sun: 4.2, fog: 0.0012,
    weather: { heat: 1 },
    terrain: { kind: 'coastal', amp: 3, freq: 1 / 250, base: 4 },
    sea: { axis: 'x', sign: 1, at: 380 },
    rivers: [{ pts: [[-520, -120], [-200, -100], [100, -160], [380, -140]], w: 22 }],
    ground: ['grassSparse', 'dryGround', 'rock', 'sand'],
    roads: [
      { pts: [[300, -500], [300, 500]], w: 18 },
      { pts: [[-500, 60], [300, 60]], w: 14 },
      { pts: [[-500, -300], [300, -300]], w: 14 },
      { pts: [[-100, -500], [-100, 500]], w: 14 },
      { pts: [[100, -500], [100, -160], [60, 60], [80, 500]], w: 12 },
      { pts: [[-500, 300], [300, 300]], w: 12 },
    ],
    districts: [
      { x: 180, z: -380, w: 220, d: 160, style: 'oldcity', block: 40 },
      { x: -250, z: 180, w: 280, d: 200, style: 'shops', block: 42 },
      { x: 180, z: 180, w: 200, d: 200, style: 'urban', block: 46 },
      { x: -250, z: -300, w: 280, d: 200, style: 'urban', block: 50 },
      { x: -100, z: 420, w: 700, d: 140, style: 'techpark', block: 64 },
      { x: -350, z: -30, w: 250, d: 120, style: 'industrial', block: 60 },
    ],
    landmarks: [
      { kind: 'lighthouse', x: 345, z: 110, h: 46, stripes: ['#e8e4dc', '#c0392b'], egg: E('marinalh', 'Marina Lighthouse', 'Marina: the world\'s second-longest urban beach. Swimming not allowed. Sundal mandatory.', 20) },
      { kind: 'central_station', x: 150, z: -250, egg: E('central', 'Chennai Central', 'Red Indo-Saracenic beauty. Train to Coimbatore delayed by 1 hour, platform changed 3 times.', 40) },
      { kind: 'gopuram', x: 200, z: 120, tiers: 7, h: 38, egg: E('gopuram', 'Temple Gopuram', 'Thousands of hand-painted figures. Please remove your shoes before looting. Just kidding. But respect.', 30) },
      { kind: 'tower', x: 0, z: -180, h: 60, w: 22, name: 'LIC', egg: E('lic', 'The LIC Building', 'Once the tallest building in India. Still the tallest building in every Chennai uncle\'s heart.', 25) },
      { kind: 'stadium', x: -130, z: -150, egg: E('chepauk', 'Chepauk', 'Whistle podu! Yellow jersey mandatory in this zone. Thala fans get +10 morale.', 50) },
      { kind: 'metro', pts: [[-100, -480], [-100, 480]], color: '#1e88e5', name: 'CHENNAI METRO', eggAt: [-100, 200] },
    ],
    props: [
      { kind: 'stall', x: 360, z: 40, rot: 3, sign: ['சுண்டல்', 'SUNDAL ₹10'], color: '#ffb300', egg: E('sundal', 'Sundal Anna', 'Sundal ₹10. Sea breeze free. Sand in your shoes: complimentary, lifetime.') },
      { kind: 'tanker', x: -200, z: 85, rot: 0, egg: E('tanker', 'Metro Water Tanker', 'The most awaited release of the summer. 40 kudams in a queue. Nobody jumps this line.') },
      { kind: 'stall', x: -80, z: 80, rot: 0, sign: ['டிகிரி காபி', 'DEGREE COFFEE · DABARA SET'], color: '#6d4c41', egg: E('degree', 'Degree Coffee', 'Served in a dabara-tumbler. Ask for a paper cup and the owner will pretend not to hear.') },
      { kind: 'sign', x: 280, z: -40, rot: 1, text: ['TODAY: HOTTEST', 'Chennai weather: Hot · Hotter · Hottest'], egg: E('heat', 'Chennai Heat', 'Sprinting in the sun drains stamina faster here. Chennai people just call this "winter".') },
      { kind: 'stall', x: -300, z: 240, rot: 1, sign: ['COOLING GLASS ₹99', 'Superstar style guaranteed'], color: '#212121', egg: E('coolingglass', 'Cooling Glass', 'Cooling glass ₹99. Flip it on with style or it doesn\'t count.') },
      { kind: 'sign', x: 120, z: 40, rot: 2, text: ['வட போச்சே!', 'Vada poche — you missed the loot'], egg: E('vadapoche', 'Vada Poche!', 'Vada poche! The loot was right here. Someone faster took it.') },
      { kind: 'auto_sign', x: 290, z: 200, rot: 1, text: ['METER PODUNGA?', 'Meter illa sir'], egg: E('cauto', 'Auto Meter', '"Meter podunga!" — "Meter repair, sir. Just give 200."') },
      { kind: 'stall', x: 40, z: 300, rot: 2, sign: ['பிரியாணி', 'BIRYANI · 45 MIN QUEUE'], color: '#e65100', egg: E('biryani', 'Biryani Queue', 'Sunday biryani queue: 45 minutes. Totally worth it. Blue zone can wait.') },
      { kind: 'billboard', x: -20, z: 330, rot: 0, text: ['NAMMA CHENNAI', 'Madras nalla Madras'], neon: '#ffb000', egg: E('nammachennai', 'Namma Chennai', 'The selfie point. Everybody has this picture. Now you do too.') },
      { kind: 'sign', x: -300, z: -160, rot: 0, text: ['CYCLONE WARNING', 'School holiday declared at 5 AM'], egg: E('cyclone', 'Cyclone Season', 'School holiday announced at 5 AM, after everyone is already dressed.') },
      { kind: 'jam', x: 300, z: -130, len: 60, dir: 'z', egg: E('kathipara', 'Kathipara Loop', 'Entered the flyover hopeful, exited in Guindy. Or Porur. Nobody knows.') },
    ],
    trees: { kinds: ['coconut', 'neem', 'coconut', 'palmyra'], count: 900 },
    vehicles: ['auto', 'auto', 'auto', 'bike', 'jeep'], vehicleCount: 16,
    signs: ['சரவணா ஸ்டோர்ஸ்', 'MADRAS CAFE', 'SILKS & SAREES', 'சைவ உணவகம்', 'KUMBAKONAM COFFEE', 'MOBILE PLANET', 'JIGARTHANDA', 'IDLI KADAI', 'GOLD PALACE', 'MESS - MEALS READY', 'AMMA UNAVAGAM', 'SWEETS & SAVOURIES'],
    neon: ['#ffb000', '#ff3f8e', '#2de2e6', '#ffe14d'],
    walls: ['#f6e7c1', '#f2c6a0', '#cfe3e8', '#e8e8e8', '#f0d58c', '#e6c3d4', '#c9e4c5', '#e0b98c'],
    roofs: ['#9e5a3c', '#8a4b31'],
    mechanics: { heat: true },
    food: { id: 'rosemilk', name: 'Rose Milk', kind: 'boost', amount: 50, time: 3, desc: 'Ice-cold rose milk. Fights the heat. +50 boost.' },
    zoneMsgs: ['Zone varudhu, odu da!', 'The zone is coming — run, da!'],
    killVerbs: ['sent to Marina', 'vada-poched', 'whistle-podu-ed', 'melted'],
    win: 'WINNER WINNER BIRYANI DINNER',
    plane: 'Madras Air TN-01',
    bots: ['WhistlePodu', 'DegreeCoffee', 'MarinaMachan', 'SundalSniper', 'CoolingGlassKing', 'VadaPoche', 'ThalaFan07', 'KathiparaLost', 'BiryaniQueue', 'AutoAnnaTN', 'TNagarShopper', 'MylaporeMami', 'HotterHottest', 'Machi', 'IdliSambar', 'JigarthandaJi', 'NannariSherbet', 'CentralStation', 'Kuthu_Dancer', 'OMR_Coder'],
    tips: ['Chennai heat: stamina drains faster while sprinting in the open.', 'Rose Milk gives +50 boost and cools you down.', 'The lighthouse gives a sniper view over the whole beach.', 'Water tankers are cover. Very popular cover.'],
  },

  // ------------------------------------------------------------------ THIRUVANANTHAPURAM
  {
    id: 'trivandrum', name: 'Trivandrum', native: 'തിരുവനന്തപുരം', state: 'Kerala',
    tagline: 'Try saying Thiruvananthapuram three times fast',
    blurb: 'Temple towers, a secretariat that has hosted every protest ever, Technopark and Kovalam sunsets.',
    sky: 'qwantani_sunset_puresky', exposure: 1.0, env: 1.0, sun: 2.8, fog: 0.0018,
    weather: {},
    terrain: { kind: 'hills', amp: 16, freq: 1 / 300, base: 8 },
    sea: { axis: 'z', sign: 1, at: 390 },
    ground: ['grass', 'redDirt', 'rock', 'sand'],
    lakes: [{ x: -60, z: 95, r: 22, pond: true }],
    roads: [
      { pts: [[-60, -500], [-60, 380]], w: 14 },
      { pts: [[-500, -120], [500, -120]], w: 14 },
      { pts: [[-500, 200], [500, 200]], w: 12 },
      { pts: [[-60, 200], [-250, 360]], w: 10 },
      { pts: [[250, -500], [250, 380]], w: 14 },
      { pts: [[-500, -380], [250, -380]], w: 10 },
    ],
    districts: [
      { x: 60, z: 50, w: 200, d: 200, style: 'shops', block: 40 },
      { x: -240, z: 40, w: 260, d: 240, style: 'kerala', block: 50 },
      { x: -60, z: -270, w: 260, d: 200, style: 'colonial', block: 48 },
      { x: 380, z: -150, w: 220, d: 280, style: 'techpark', block: 70 },
      { x: 150, z: 300, w: 300, d: 120, style: 'kerala', block: 50 },
      { x: -300, z: -300, w: 240, d: 200, style: 'urban', block: 50 },
    ],
    landmarks: [
      { kind: 'gopuram', x: -60, z: 40, tiers: 7, h: 34, kerala: true, egg: E('padmanabha', 'Temple Tower', 'Seven tiers of stone. The pond in front reflects it perfectly at sunset. Respect the dress code.', 30) },
      { kind: 'secretariat', x: -20, z: -175, egg: E('secretariat', 'The Secretariat', 'Protest number 4,382 of the year. Topic: yes. Tea stall outside: always open.', 45) },
      { kind: 'lighthouse', x: -290, z: 385, h: 36, stripes: ['#f1f1f1', '#c62828'], egg: E('kovalam', 'Kovalam Lighthouse', 'The lighthouse has seen more foreign tourists than your passport ever will.', 20) },
      { kind: 'napier', x: 130, z: -300, egg: E('napier', 'Napier Museum', 'Kerala roof, Indo-Saracenic walls, 150 years old. The zoo next door is watching you loot.', 30) },
      { kind: 'port_cranes', x: 300, z: 400, egg: E('vizhinjam', 'Vizhinjam Port', 'Deep-water port. The cranes are taller than the plot of most serials.', 40) },
    ],
    props: [
      { kind: 'harthal', x: 60, z: 50, egg: E('harthal', 'Harthal Day', 'Harthal today. Every shop is closed. Only the loot is open for business.', 60) },
      { kind: 'billboard', x: -60, z: -420, rot: 0, text: ['THIRUVANANTHAPURAM', 'Say it 3× fast, win a free chaya'], neon: '#2de2e6', egg: E('longname', 'The Long Name', 'THIRUVANANTHAPURAM. Locals just say "TVM". Or "Trivandrum". Or wave in that direction.') },
      { kind: 'bus', x: -40, z: -120, rot: 1, egg: E('ksrtc', 'KSRTC', 'The KSRTC driver waits for no one. Especially not you. Especially not today.') },
      { kind: 'sign', x: 250, z: -80, rot: 3, text: ['TECHNOPARK', 'Code · Chaya · Canada visa'], egg: E('technopark', 'Technopark', 'Where Malayalis write code and dream of Canada. Or the Gulf. Or both.') },
      { kind: 'sign', x: 0, z: 190, rot: 2, text: ['ALIYA, ENTHUVAADE?', 'Aliya = bro · Enthuvaade = what\'s up'], egg: E('aliya', 'Trivandrum Slang', 'Crash course: "Aliya" = bro, "Enthuvaade" = what\'s up, "Pinne?" = and then? You\'re fluent now.') },
      { kind: 'stall', x: 170, z: 190, rot: 2, sign: ['SHAWARMA', 'Kerala state food since 2012'], color: '#e67e22', egg: E('shawarma', 'Shawarma Stall', 'Kerala\'s unofficial state food. Ask for "extra mayo" and watch them smile.') },
      { kind: 'stall', x: -200, z: 210, rot: 0, sign: ['സദ്യ', 'SADHYA · 26 DISHES · 1 LEAF'], color: '#27ae60', egg: E('sadhya', 'Sadhya', '26 dishes, 1 banana leaf, 0 cutlery. Fold the leaf towards you when done.') },
      { kind: 'sign', x: 120, z: -40, rot: 1, text: ['SUDDEN RAIN', 'Umbrella opens → rain stops. Every time.'], egg: E('suddenrain', 'Sudden Rain', 'Open umbrella: rain stops. Close umbrella: rain starts. Kerala physics.') },
    ],
    trees: { kinds: ['coconut', 'coconut', 'raintree', 'banana', 'coconut'], count: 1400 },
    vehicles: ['auto', 'auto', 'bike', 'jeep', 'bus'], vehicleCount: 13,
    signs: ['ചായക്കട', 'KERALA SAREES', 'AYURVEDA', 'GOLD PALACE', 'MILMA BOOTH', 'ബേക്കറി', 'HOTEL SREE', 'SHAWARMA HUB', 'MOBILE PARK', 'COFFEE HOUSE', 'TAILORS', 'BOOK STALL'],
    neon: ['#2de2e6', '#ff3f8e', '#ffb000'],
    walls: ['#f3e6c8', '#bfe0d0', '#f0c9a0', '#d9e8f0', '#f2d7e0', '#e8e0a8', '#c5d8b5', '#fff6e0'],
    roofs: ['#a8472f', '#8f3a28'],
    mechanics: { harthal: true },
    food: { id: 'sharjahshake', name: 'Sharjah Shake', kind: 'boost', amount: 50, time: 3, desc: 'Banana + milk + Horlicks energy. +50 boost.' },
    zoneMsgs: ['Aliya, zone varunnu, odikko!', 'Bro, the zone is coming — run!'],
    killVerbs: ['harthal-ed', 'sent to the Secretariat', 'KSRTC-ed', 'aliya-ed'],
    win: 'WINNER WINNER SADHYA DINNER',
    plane: 'Anantha Airways KL-01',
    bots: ['AliyaSniper', 'HarthalHero', 'TechnoparkTechie', 'KovalamKid', 'KSRTC_Driver', 'SadhyaSlayer', 'SharjahShake', 'Pinne', 'CanadaVisa', 'ShawarmaShark', 'NapierNinja', 'VizhinjamCrane', 'MilmaMan', 'SecretariatStriker', 'PazhamPori', 'TVM_Pro', 'EnthuvaadeAliya', 'CoffeeHouse', 'ChaalaMarket', 'TrivandrumTiger'],
    tips: ['Harthal: shops in the market have their shutters down. Use side entrances.', 'The Secretariat has a long roof — sniper heaven.', 'Kovalam lighthouse overlooks the southern beach.'],
  },

  // ------------------------------------------------------------------ THRISSUR
  {
    id: 'thrissur', name: 'Thrissur', native: 'തൃശ്ശൂർ', state: 'Kerala',
    tagline: 'The whole town literally revolves around one round',
    blurb: 'Pooram night: caparisoned elephants, umbrellas, fireworks and gold shops around Swaraj Round.',
    sky: 'qwantani_night_puresky', exposure: 1.1, env: 0.34, sun: 0.6, fog: 0.0022, fogColor: '#131a2c', bgI: 0.11, night: true,
    weather: { fireworks: true },
    terrain: { kind: 'hills', amp: 10, freq: 1 / 320, base: 8 },
    ground: ['grass', 'redDirt', 'rock', 'grassSparse'],
    ringRoad: { x: 0, z: 0, r: 130, w: 14 },
    roads: [
      { pts: [[0, -130], [0, -500]], w: 12 }, { pts: [[0, 130], [0, 500]], w: 12 },
      { pts: [[-130, 0], [-500, 0]], w: 12 }, { pts: [[130, 0], [500, 0]], w: 12 },
      { pts: [[92, -92], [380, -380]], w: 10 }, { pts: [[-92, 92], [-380, 380]], w: 10 },
      { pts: [[-500, -300], [500, -300]], w: 10 },
    ],
    districts: [
      { x: 230, z: 230, w: 220, d: 220, style: 'shops', block: 42 },
      { x: -250, z: -230, w: 260, d: 240, style: 'kerala', block: 52 },
      { x: 260, z: -200, w: 240, d: 180, style: 'urban', block: 50 },
      { x: -260, z: 250, w: 240, d: 230, style: 'kerala', block: 52 },
      { x: 250, z: -410, w: 400, d: 120, style: 'urban', block: 50 },
    ],
    ringShops: true,
    landmarks: [
      { kind: 'kerala_temple', x: 0, z: -10, egg: E('vadakkunnathan', 'The Temple on the Hill', 'The town literally revolves around it. Swaraj Round goes around the temple grounds — the only road you need.', 40) },
      { kind: 'elephants', x: 0, z: 75, n: 9, egg: E('pooram', 'Pooram', '15 elephants, a million people, zero personal space. The mother of all festivals.', 30) },
      { kind: 'church', x: 250, z: -110, color: '#f5f2ea', spires: 3, tall: true, egg: E('basilica', 'The Basilica', 'Tallest church spires in the region. Also the best sniper nest in Thrissur. Please be respectful.', 25) },
      { kind: 'waterfall', x: 420, z: 300, h: 26, egg: E('athirappilly', 'The Big Waterfall', 'The waterfall from that one very big movie. Don\'t jump. Or do — you have a parachute somewhere.', 30) },
    ],
    props: [
      { kind: 'sign', x: 150, z: 20, rot: 1, text: ['916 HALLMARK', 'More gold shops than people'], egg: E('gold', 'Gold Capital', 'Thrissur has more jewellery shops per metre than any place on Earth. Loot tip: it\'s all 916.') },
      { kind: 'puli', x: -150, z: 60, egg: E('pulikali', 'Puli Kali', 'Tigers with painted bellies dancing to chenda. Most dangerous "bot" on the map.') },
      { kind: 'sign', x: -150, z: -40, rot: 3, text: ['KURI DRAW TODAY', 'Monthly chit fund · uncle is confident'], egg: E('kuri', 'Kuri', 'Monthly kuri draw today. Uncle has been "confident" for 14 months.') },
      { kind: 'sign', x: 40, z: 150, rot: 0, text: ['ENTE GURUVAYURAPPA!', 'Thrissur for "oh my god"'], egg: E('slang', 'Thrissur Slang', '"Ente Guruvayurappa!" = OMG. "Gadi" = bro. "Ishtaayi" = liked it. You\'re a local now.') },
      { kind: 'stall', x: 140, z: -60, rot: 3, sign: ['പഴംപൊരി', 'PAZHAM PORI + CHAYA'], color: '#f39c12', egg: E('pazhampori', 'Pazham Pori', 'Evening ritual: pazham pori and chaya. It is not optional. It is the law.') },
      { kind: 'bank', x: -140, z: 110, egg: E('banks', 'Bank Town', 'Thrissur is the birthplace of several banks. Interest rates on loot are high here.') },
      { kind: 'kudamattam', x: 0, z: 110, egg: E('kudamattam', 'Kudamattam', 'The umbrella-swap battle. Hundreds of silk umbrellas, changed in seconds. Your helmet has no chance.', 20) },
    ],
    trees: { kinds: ['coconut', 'raintree', 'coconut', 'banana'], count: 1200 },
    vehicles: ['auto', 'auto', 'bike', 'jeep', 'bus'], vehicleCount: 13,
    signs: ['തൃശ്ശൂർ ജ്വല്ലറി', 'GOLD & DIAMONDS', 'SILK HOUSE', 'KURI & CHITS', 'ബേക്കറി', 'HOTEL POORAM', 'BANK', 'VEGETARIAN HOTEL', 'TEXTILES', 'CHENDA CLASSES', 'GOLD LOAN'],
    neon: ['#ffb000', '#ff3f8e', '#2de2e6', '#ffd700'],
    walls: ['#f3e6c8', '#bfe0d0', '#f0c9a0', '#f7f1e3', '#f2d7e0', '#e8e0a8'],
    roofs: ['#a8472f', '#8f3a28'],
    mechanics: { fireworks: true, swarajRound: true },
    food: { id: 'pazhampori', name: 'Pazham Pori', kind: 'heal', amount: 20, time: 3, desc: 'Banana fritter. Heals 20 HP.' },
    zoneMsgs: ['Ente Guruvayurappa, zone varunnu!', 'Oh my god, the zone is coming!'],
    killVerbs: ['sent round Swaraj Round', 'kudamattam-ed', 'fireworked', 'gadi-ed'],
    win: 'WINNER WINNER PAZHAM PORI DINNER',
    plane: 'Pooram Airlines KL-08',
    bots: ['SwarajRounder', 'PooramPro', 'ChendaMelam', 'GoldLoanGuru', 'PuliKaliTiger', 'Gadi', 'KuriUncle', 'Ishtaayi', 'KudamattamKing', 'Vedikkettu', 'ThrissurThunder', 'ElephantWhisperer', 'PazhamPoriPower', 'Nettipattam', '916Hallmark', 'BasilicaBell', 'ShakthanMarket', 'EnteGuruvayurappa', 'PooramPyro', 'RoundAbout'],
    tips: ['Night map. Fireworks light up the sky — and you.', 'Drive a full lap around Swaraj Round for a surprise.', 'Elephants are huge cover. Don\'t shoot the elephants.', 'The Basilica spire is the highest point in town.'],
  },

  // ------------------------------------------------------------------ DELHI
  {
    id: 'delhi', name: 'Delhi', native: 'दिल्ली', state: 'NCT of Delhi',
    tagline: 'AQI 999, attitude 200%',
    blurb: 'India Gate, Qutub Minar, Chandni Chowk wires and a smog so thick the zone is hard to see.',
    sky: 'kloofendal_28d_misty_puresky', exposure: 1.0, env: 0.9, sun: 2.0, fog: 0.0055, fogColor: '#b9ab94',
    weather: { smog: 1 },
    terrain: { kind: 'flat', amp: 5, freq: 1 / 300, base: 6 },
    rivers: [{ pts: [[380, -520], [360, -200], [400, 100], [370, 520]], w: 60 }],
    ground: ['grassSparse', 'dryGround', 'rock', 'sand'],
    roads: [
      { pts: [[-300, 150], [250, 150]], w: 22 },
      { pts: [[0, -500], [0, 500]], w: 16 },
      { pts: [[-500, -60], [300, -60]], w: 14 },
      { pts: [[-500, 330], [300, 330]], w: 14 },
      { pts: [[-330, -500], [-330, 500]], w: 14 },
      { pts: [[200, -500], [200, 500]], w: 12 },
    ],
    districts: [
      { x: 90, z: -320, w: 200, d: 200, style: 'oldcity', block: 36 },
      { x: -170, z: 20, w: 220, d: 140, style: 'bungalow', block: 60 },
      { x: -170, z: 240, w: 260, d: 140, style: 'bungalow', block: 60 },
      { x: -200, z: -290, w: 200, d: 220, style: 'urban', block: 46 },
      { x: 110, z: 420, w: 200, d: 130, style: 'urban', block: 48 },
      { x: -420, z: 50, w: 120, d: 520, style: 'shops', block: 40 },
    ],
    landmarks: [
      { kind: 'india_gate', x: 0, z: 150, egg: E('indiagate', 'India Gate', '42 metres of sandstone. The ice-cream wala out front has the best business model in Delhi.', 30) },
      { kind: 'qutub', x: -380, z: 400, egg: E('qutub', 'Qutub Minar', '73 metres tall. Still shorter than your loot wishlist.', 25) },
      { kind: 'cp_circle', x: 90, z: -60, r: 80, egg: E('cp', 'Connaught Place', 'Every block is "the" block. You\'re lost now. Everyone is. That\'s the design.', 50) },
      { kind: 'red_fort', x: 250, z: -400, egg: E('redfort', 'Red Fort Walls', 'Red sandstone walls, 2 km of them. Great cover, terrible for sneaking in.', 40) },
      { kind: 'metro', pts: [[-200, -480], [-200, 480]], color: '#fbc02d', name: 'DELHI METRO', eggAt: [-200, 0], egg: E('dmetro', 'Delhi Metro', '"Please mind the gap." Also mind the couple filming a dance reel in coach 3.', 14) },
    ],
    props: [
      { kind: 'aqi', x: 30, z: 120, rot: 2, egg: E('aqi', 'AQI Board', 'AQI 999. Breathing here = 40 cigarettes a day. Helmet Lv.3 does not help.') },
      { kind: 'stall', x: 60, z: -250, rot: 1, sign: ['छोले भटूरे', 'CHOLE BHATURE · SINCE 1952'], color: '#e53935', egg: E('cholebhature', 'Chole Bhature', 'Breakfast, lunch, dinner, therapy. Delhi\'s answer to everything.') },
      { kind: 'suv', x: -30, z: -60, rot: 0, egg: E('baap', '"Mera Baap Kaun Hai"', 'Sticker on the SUV: "Tu jaanta nahi mera baap kaun hai?" Nobody knows. He\'s also stuck in traffic.') },
      { kind: 'wires', x: 90, z: -330, egg: E('wires', 'Chandni Chowk Wiring', 'Approved by nobody. Working since 1970. Do not touch. Do not even look.', 25) },
      { kind: 'stall', x: 120, z: -380, rot: 3, sign: ['MONKEY CAP ₹150', 'Winter essential · fashion optional'], color: '#5d4037', egg: E('monkeycap', 'Monkey Cap', 'Delhi winter survival kit: monkey cap, muffler, and a heater you\'ll fight your sibling for.') },
      { kind: 'stall', x: 40, z: -410, rot: 0, sign: ['परांठे वाली गली', '32 FILLINGS · 1 HEART'], color: '#ff8f00', egg: E('paranthe', 'Paranthe Wali Gali', '32 fillings, all fried in ghee. Your cardiologist has marked this location on the map.') },
      { kind: 'parking_fight', x: -250, z: -200, egg: E('parking', 'Parking Dispute', 'Day 3 of the parking dispute. Neither car will reverse. Both families have brought lunch.') },
      { kind: 'baraat', x: -330, z: 180, egg: E('baraat', 'Baraat', 'A baraat on the main road. Traffic stops, nagin dance begins. Groom arrives 3 hours late. On a horse.', 20) },
      { kind: 'stall', x: -330, z: 90, rot: 1, sign: ['MOMOS', 'Red chutney melts armour'], color: '#d32f2f', egg: E('momos', 'Delhi Momos', 'The red chutney here can melt a Level 3 vest. Eat at your own risk.') },
      { kind: 'sign', x: 210, z: 20, rot: 3, text: ['DILLI KI SARDI', 'Visibility 20 m · attitude 200%'], egg: E('sardi', 'Dilli ki Sardi', 'Winter fog so thick you\'ll hear the enemy before you see them.') },
    ],
    trees: { kinds: ['neem', 'raintree', 'neem', 'dry'], count: 1000 },
    vehicles: ['auto', 'auto', 'bike', 'jeep', 'jeep'], vehicleCount: 15,
    signs: ['शर्मा स्वीट्स', 'DILLI DARBAR', 'CHAAT CORNER', 'गुप्ता जनरल स्टोर', 'KAROL BAGH MOBILES', 'PUNJABI DHABA', 'PAAN BHANDAR', 'WEDDING CARDS', 'JALEBI WALA', 'BUTTER CHICKEN', 'RAJMA CHAWAL', 'DHABA 24x7', 'LASSI CORNER'],
    neon: ['#ffb000', '#ff3f8e', '#2de2e6'],
    walls: ['#e7d3b0', '#d9b99b', '#cbbba0', '#e8e0d0', '#c9a27e', '#b8a48c', '#efe4cf'],
    roofs: ['#7d4a32'],
    mechanics: { smog: true },
    food: { id: 'cholebhature', name: 'Chole Bhature', kind: 'heal', amount: 35, time: 5, desc: 'Heals 35 HP. Makes you sleepy later.' },
    zoneMsgs: ['Bhai zone aa raha hai, bhaag!', 'Bro, the zone is coming — run!'],
    killVerbs: ['parked', 'challaned', 'sent to Noida', 'smogged'],
    win: 'WINNER WINNER CHOLE BHATURE DINNER',
    plane: 'Dilli Darshan Air DL-3C',
    bots: ['MeraBaapKaunHai', 'CholeBhatureKing', 'AQI999', 'SardiMeinGarmi', 'CP_Lost', 'MetroDancer', 'ParkingPrince', 'BhaiSahab', 'MonkeyCapMafia', 'KarolBaghKid', 'LajpatNagarLoot', 'JugaadJatt', 'ParantheWala', 'DelhiBelly', 'SouthExSniper', 'ChandniChowkChamp', 'NoidaNinja', 'RajpathRunner', 'MomosMaster', 'BaraatBand'],
    tips: ['Smog: visibility is terrible. Listen for footsteps.', 'The AQI meter on your HUD is just for vibes. And despair.', 'Qutub Minar is climbable — best sniper spot in the south.', 'Chandni Chowk lanes are narrow: shotguns rule.'],
  },

  // ------------------------------------------------------------------ GURUGRAM
  {
    id: 'gurugram', name: 'Gurugram', native: 'गुरुग्राम', state: 'Haryana',
    tagline: 'Millennium City, now with free gondolas',
    blurb: 'Glass towers, neon, cranes that never finish and roads that turn into lakes. Night map.',
    sky: 'qwantani_dusk_2_puresky', exposure: 0.85, env: 0.75, sun: 0.7, fog: 0.0026, fogColor: '#231f38', bgI: 0.45, night: true,
    weather: { rain: 0.35 },
    terrain: { kind: 'flat', amp: 5, freq: 1 / 280, base: 6 },
    lakes: [
      { x: 0, z: 120, r: 36, flood: true }, { x: -250, z: -60, r: 30, flood: true }, { x: 180, z: 330, r: 28, flood: true }, { x: 250, z: -250, r: 26, flood: true },
    ],
    ground: ['grassSparse', 'dryGround', 'rock', 'sand'],
    roads: [
      { pts: [[-500, 380], [-300, 250], [0, 120], [300, -40], [500, -120]], w: 22 },
      { pts: [[-250, -500], [-250, 500]], w: 14 },
      { pts: [[0, -500], [0, 500]], w: 14 },
      { pts: [[250, -500], [250, 500]], w: 14 },
      { pts: [[-500, -250], [500, -250]], w: 14 },
      { pts: [[-500, -60], [500, -60]], w: 12 },
    ],
    districts: [
      { x: 125, z: -380, w: 230, d: 200, style: 'glass', block: 64 },
      { x: -125, z: -155, w: 220, d: 170, style: 'techpark', block: 64 },
      { x: 380, z: -300, w: 220, d: 360, style: 'condo', block: 70 },
      { x: -380, z: 100, w: 220, d: 300, style: 'shops', block: 40 },
      { x: 130, z: 300, w: 220, d: 300, style: 'condo', block: 70 },
      { x: -130, z: 350, w: 220, d: 250, style: 'urban', block: 48 },
      { x: 380, z: 200, w: 220, d: 200, style: 'industrial', block: 60 },
    ],
    landmarks: [
      { kind: 'cyber_hub', x: 125, z: -150, egg: E('cyberhub', 'Cyber Hub', '₹600 cold brew. ₹0 parking available. Every table is discussing a startup that will pivot twice.', 35) },
      { kind: 'toll', x: -400, z: 318, egg: E('toll', 'Toll Plaza', 'Pay ₹100 to wait 30 minutes. FASTag beeps, nothing moves.', 30) },
      { kind: 'mall', x: -125, z: 60, name: 'AMBI MALL', egg: E('gmall', 'The Mall', 'The only place in the city with working drainage.', 40) },
      { kind: 'metro', pts: [[-480, -270], [480, -270]], color: '#00bcd4', name: 'RAPID METRO', eggAt: [100, -270] },
      { kind: 'cranes', x: 380, z: 60, n: 3, egg: E('crane', 'Under Construction', 'Under construction since 2008. Possession: "next year". Every year.', 50) },
    ],
    props: [
      { kind: 'boat', x: 0, z: 120, egg: E('venice', 'Gurugram Venice', 'Gondola service to Cyber City now live. Please don\'t feed the traffic cones.', 30) },
      { kind: 'cows', x: 150, z: 20, n: 4, egg: E('cows', 'Highway Cows', 'Expressway speed limit: 100 km/h. Cow speed limit: 0. Cows have right of way. Always.') },
      { kind: 'billboard', x: 20, z: -330, rot: 1, text: ['HUSTLE CULTURE', '14h work · 4h commute · 0h sleep'], neon: '#ff3f8e', egg: E('hustle', 'Hustle Culture', 'Rise and grind. Grind and grind. Grind some more. Weekend? Never heard of it.') },
      { kind: 'billboard', x: -260, z: 180, rot: 1, text: ['KAL SE PAKKA GYM', 'Membership since 2019 · visits: 3'], neon: '#b4ff39', egg: E('gym', 'Kal se Pakka Gym', 'Every Gurugram resident has a gym membership. Some have even seen the gym.') },
      { kind: 'sign', x: -250, z: -40, rot: 1, text: ['NOT A POTHOLE', 'It\'s a lake with a PIN code'], egg: E('lakepin', 'Lake with PIN Code', 'The municipal records list this as a road. The fish disagree.') },
      { kind: 'billboard', x: 250, z: 180, rot: 3, text: ['LUXURY CONDOS', 'Only 45 mins from Cyber City*'], neon: '#2de2e6', egg: E('condo', 'Luxury Condo', '*45 minutes at 3 AM with no traffic and a helicopter.') },
      { kind: 'billboard', x: -20, z: 420, rot: 0, text: ['UNICORN HQ', 'Now "hybrid" · the unicorn left'], neon: '#8e44ad', egg: E('unicorn', 'Unicorn HQ', 'Raised $200M, burned $200M, now "focusing on profitability". The office plants were laid off too.') },
      { kind: 'sign', x: 250, z: -120, rot: 3, text: ['FRIDAY NIGHT', '"Just one drink" — 2 AM'], egg: E('friday', 'Friday Night', '"Just one drink" said nobody truthfully in Sector 29.') },
    ],
    trees: { kinds: ['neem', 'dry', 'raintree'], count: 700 },
    vehicles: ['jeep', 'jeep', 'auto', 'bike', 'boat', 'boat'], vehicleCount: 15,
    signs: ['CYBER CAFE', 'COLD BREW CO.', 'FOOD COURT', 'THEKA', 'SECTOR 29', 'CO-WORKING', 'DHABA', 'PG FOR GIRLS', 'CRYPTO EXCHANGE', 'PROPERTY DEALER', 'MOMOS', 'SALON & SPA'],
    neon: ['#ff3f8e', '#2de2e6', '#b4ff39', '#8e44ad', '#ffb000'],
    walls: ['#d8d8d8', '#c8c3bb', '#e6e1d8', '#b9b4ac', '#d4cbbd'],
    roofs: ['#555'],
    mechanics: { flooding: true },
    food: { id: 'coldbrew', name: 'Cold Brew', kind: 'boost', amount: 45, time: 3, desc: '₹600 cold brew. +45 boost, -₹600.' },
    zoneMsgs: ['Bhai zone aa gaya, nikal le!', 'Bro, zone\'s here — get out!'],
    killVerbs: ['laid off', 'sent to the toll plaza', 'pivoted', 'waterlogged'],
    win: 'WINNER WINNER BUTTER CHICKEN DINNER',
    plane: 'Hustle Airways HR-26',
    bots: ['HustleBro', 'ColdBrewCEO', 'Sector29', 'KalSeGym', 'CyberHubHero', 'TollTaxTitan', 'GondolaGuy', 'CryptoChacha', 'UnicornHunter', 'LayoffLegend', 'PivotPrince', 'FastagFail', 'WaterloggedWala', 'GolfCourseRoad', 'DLF_Phase5', 'SohnaRoadRage', 'StartupSaurabh', 'PropertyDealer', 'CondoKing', 'JugaadJeet'],
    tips: ['Flooded roads slow you down. Boats spawn in the big puddles.', 'Night map: neon lights up the towers. Muzzle flashes are visible from far away.', 'Cyber Hub rooftops give great sight lines.'],
  },

  // ------------------------------------------------------------------ MEGHALAYA
  {
    id: 'meghalaya', name: 'Meghalaya', native: 'Shillong · Sohra', state: 'Meghalaya',
    tagline: 'Abode of clouds — your socks will never be dry again',
    blurb: 'Living root bridges, the wettest place on Earth, crystal-clear Dawki and the rock capital of India.',
    sky: 'kloofendal_misty_morning_puresky', exposure: 1.05, env: 1.0, sun: 1.4, fog: 0.0042, fogColor: '#a9b4b3',
    weather: { rain: 0.8 },
    terrain: { kind: 'hills', amp: 55, freq: 1 / 340, base: 30 },
    lakes: [{ x: 0, z: -330, r: 110, lake: true }],
    rivers: [{ pts: [[520, 180], [350, 280], [200, 330], [-40, 300], [-150, 180], [-260, 230]], w: 24, clear: true }],
    ground: ['grass', 'forest', 'mossyRock', 'grassPath'],
    roads: [
      { pts: [[-500, -120], [-220, -100], [0, -150], [200, -100], [500, -140]], w: 10 },
      { pts: [[-220, -100], [-230, 150], [-300, 500]], w: 9 },
      { pts: [[200, -100], [260, 150], [330, 500]], w: 9 },
      { pts: [[0, -150], [-40, 60], [60, 450]], w: 9 },
    ],
    districts: [
      { x: -200, z: -40, w: 220, d: 170, style: 'hill', block: 40 },
      { x: 330, z: -30, w: 200, d: 150, style: 'village', block: 46 },
      { x: -330, z: 350, w: 200, d: 150, style: 'village', block: 46 },
      { x: 120, z: 150, w: 180, d: 120, style: 'hill', block: 42 },
      { x: 250, z: -330, w: 180, d: 150, style: 'village', block: 46 },
    ],
    landmarks: [
      { kind: 'root_bridge', x: -145, z: 185, rot: 1, egg: E('rootbridge', 'Living Root Bridge', 'Grown, not built. 200 years old and still stronger than your internet connection.', 20) },
      { kind: 'root_bridge', x: 200, z: 330, rot: 0 },
      { kind: 'waterfall', x: -420, z: 180, h: 60, egg: E('nohkalikai', 'The Great Falls', 'A 340-metre drop into a turquoise pool. Parachute recommended. Actually required.', 30) },
      { kind: 'rock_stage', x: -120, z: -90, egg: E('rockcapital', 'Rock Capital', 'Every third person here plays guitar better than you. The fourth one plays drums.', 30) },
      { kind: 'church', x: -260, z: -60, color: '#9fb8d8', spires: 1, egg: E('cathedral', 'Blue Cathedral', 'Sunday hymns echo over the hills. Loot quietly.', 22) },
    ],
    props: [
      { kind: 'sign', x: -190, z: 60, rot: 1, text: ['WETTEST PLACE ON EARTH', 'Your socks will never dry again'], egg: E('wettest', 'Wettest Place on Earth', '11,000+ mm of rain a year. The rain never stops here. It just changes direction.') },
      { kind: 'boat', x: 360, z: 270, clear: true, egg: E('dawki', 'Dawki', 'The water is so clear the boats look like they\'re flying. Don\'t look down if you\'re scared of heights.', 25) },
      { kind: 'sign', x: 310, z: -80, rot: 2, text: ['CLEANEST VILLAGE IN ASIA', 'Please drop your loot neatly'], egg: E('mawlynnong', 'Cleanest Village', 'Bamboo dustbins on every corner. Even the bots put their shells in the bin here.') },
      { kind: 'sign', x: 0, z: -200, rot: 0, text: ['SCOTLAND OF THE EAST', 'The weather agrees'], egg: E('scotland', 'Scotland of the East', 'Pine hills, lakes, fog and rain. Scotland wishes it was this green.') },
      { kind: 'knup', x: -230, z: 30, egg: E('knup', 'Knup', 'Knup: the Khasi rain shield you wear on your back. Hands free for looting. Genius.') },
      { kind: 'stall', x: -160, z: -60, rot: 0, sign: ['JADOH · DOHNEIIONG', 'Rice + pork · ultimate boost'], color: '#8d6e63', egg: E('jadoh', 'Jadoh Stall', 'Jadoh and dohneiiong. The ultimate boost item. The bots queue for it too.') },
      { kind: 'football', x: 120, z: 90, egg: E('rainfootball', 'Rain Football', 'Football in the rain is mandatory here. Rain is not an excuse, it is the pitch condition.', 25) },
      { kind: 'jam', x: -220, z: -100, len: 50, dir: 'x', egg: E('shillongjam', 'Shillong Traffic', 'Polite, patient, permanent. Nobody honks. Everyone waits. Respect.') },
    ],
    trees: { kinds: ['pine', 'pine', 'pine', 'bamboo', 'raintree'], count: 2200 },
    vehicles: ['jeep', 'jeep', 'bike', 'boat'], vehicleCount: 11,
    signs: ['POLICE BAZAR', 'JADOH HOUSE', 'KHASI HANDLOOM', 'GUITAR STORE', 'MOMO CORNER', 'TEA STALL', 'PINE CAFE', 'MUSIC SCHOOL', 'BAKERY', 'ORANGE HONEY'],
    neon: ['#2de2e6', '#ff3f8e', '#9bff6a'],
    walls: ['#e57373', '#64b5f6', '#81c784', '#fff176', '#ba68c8', '#4db6ac', '#ffb74d', '#f0f0f0'],
    roofs: ['#b71c1c', '#1565c0', '#2e7d32', '#6d4c41'],
    mechanics: { slippery: true },
    food: { id: 'jadoh', name: 'Jadoh', kind: 'heal', amount: 30, time: 4, desc: 'Rice cooked with pork. Heals 30 HP.' },
    zoneMsgs: ['Ka zone ka wan! Leit noh!', 'The zone is coming! Go now!'],
    killVerbs: ['washed away', 'root-bridged', 'rocked', 'fogged'],
    win: 'WINNER WINNER JADOH DINNER',
    plane: 'Cloud Abode Air ML-05',
    bots: ['RootBridgeRanger', 'RockCapitalRiff', 'JadohJunkie', 'CherraRain', 'DawkiDrifter', 'PineFog', 'KhasiHillsKid', 'ShillongChord', 'UmiamUmbrella', 'KnupNinja', 'PoliceBazarPro', 'MawsynramMist', 'CleanestVillage', 'GuitarHero_ML', 'OrangeHoney', 'SohraSniper', 'WardsLake', 'LaitlumLeap', 'DrumsAndDoh', 'CloudAbode'],
    tips: ['It rains all match. Footsteps are muffled — use it.', 'Wet slopes are slippery. Sprinting downhill is fast and dangerous.', 'Root bridges cross the river gorges.', 'Dawki: shallow crystal water, boats spawn nearby.'],
  },

  // ------------------------------------------------------------------ AIZAWL
  {
    id: 'aizawl', name: 'Aizawl', native: 'Aizawl · Mizoram', state: 'Mizoram',
    tagline: 'No honking. No overtaking. Only patience.',
    blurb: 'A city stacked on ridges, houses on stilts, perfect lane discipline and football on every flat patch.',
    sky: 'qwantani_morning_puresky', exposure: 0.95, env: 1.0, sun: 3.0, fog: 0.0019,
    weather: {},
    terrain: { kind: 'ridges', amp: 95, freq: 1 / 380, base: 20 },
    ground: ['grass', 'forest', 'rockTerrain', 'grassSparse'],
    roads: [
      { pts: [[-500, -60], [-250, -20], [0, 0], [250, 40], [500, 20]], w: 10, ridge: true },
      { pts: [[0, 0], [30, -250], [-20, -500]], w: 9 },
      { pts: [[0, 0], [-40, 250], [20, 500]], w: 9 },
      { pts: [[250, 40], [280, 300]], w: 8 },
    ],
    districts: [
      { x: -150, z: -30, w: 280, d: 150, style: 'hill', block: 36 },
      { x: 150, z: 30, w: 260, d: 150, style: 'hill', block: 36 },
      { x: 20, z: -230, w: 160, d: 170, style: 'hill', block: 38 },
      { x: -30, z: 240, w: 160, d: 170, style: 'hill', block: 38 },
      { x: 350, z: -300, w: 200, d: 180, style: 'village', block: 46 },
      { x: -350, z: 320, w: 200, d: 180, style: 'village', block: 46 },
    ],
    landmarks: [
      { kind: 'church', x: 300, z: 200, color: '#fafafa', spires: 2, tall: true, egg: E('solomon', 'The White Temple', 'A gleaming white church on the hill with four minaret-like towers. Sunday here: the whole city goes quiet.', 25) },
      { kind: 'stadium', x: -300, z: -150, small: true, egg: E('mizofootball', 'Football Ground', 'Mizoram is football-crazy. Every flat patch of land becomes a pitch. There are not many flat patches.', 40) },
    ],
    props: [
      { kind: 'ordered_jam', x: 0, z: 0, egg: E('discipline', 'Lane Discipline', 'Single file. No honking. No overtaking. The rest of India watches this video and cries.', 40) },
      { kind: 'bamboo', x: -80, z: 60, egg: E('cheraw', 'Cheraw', 'The bamboo dance. Miss the timing and the bamboo wins. Just like reloading under fire.') },
      { kind: 'honesty_shop', x: 120, z: -60, egg: E('nghahloh', 'Nghah Loh Dawr', 'A shop with no shopkeeper. Take what you need, leave the money in the box. The honesty is real.') },
      { kind: 'sign', x: 60, z: 90, rot: 2, text: ['TLAWMNGAIHNA', 'Help others first · except in the final circle'], egg: E('tlawm', 'Tlawmngaihna', 'The Mizo code: put others first, be selfless, be kind. Maybe revive your teammate this time.') },
      { kind: 'stall', x: -200, z: 30, rot: 2, sign: ['BAI', 'Boiled veggies + pork'], color: '#43a047', egg: E('bai', 'Bai Stall', 'Healthy, until the second helping. And the third.') },
      { kind: 'sign', x: 200, z: -40, rot: 3, text: ['DURTLANG VIEW', 'Every house is a hill station'], egg: E('view', 'The View', 'Every house in the city has a view that hill stations charge ₹8000 a night for.') },
      { kind: 'sign', x: -300, z: -40, rot: 1, text: ['SECOND GEAR ONLY', 'Hill roads · forever'], egg: E('gear', 'Second Gear Forever', 'Nobody in Aizawl has used fifth gear. Some cars don\'t know they have one.') },
      { kind: 'sign', x: 270, z: 140, rot: 1, text: ['SUNDAY', 'Everything is closed · even the bots rest'], egg: E('sunday', 'Sunday', 'Everything shuts on Sunday. Church, lunch, family, rest. Beautiful.') },
    ],
    trees: { kinds: ['pine', 'bamboo', 'raintree', 'banana'], count: 1900 },
    vehicles: ['jeep', 'jeep', 'bike', 'bike'], vehicleCount: 12,
    signs: ['BARA BAZAR', 'ZO HANDLOOM', 'MIZO KITCHEN', 'FOOTBALL STORE', 'BAKERY', 'TEA STALL', 'MOBILE ZONE', 'SAWHCHIAR HOUSE', 'ANTHURIUM FLORIST', 'CHURCH BOOKSHOP'],
    neon: ['#2de2e6', '#ff3f8e', '#ffb000'],
    walls: ['#ef9a9a', '#90caf9', '#a5d6a7', '#fff59d', '#ce93d8', '#80cbc4', '#ffcc80', '#eceff1', '#f48fb1'],
    roofs: ['#c62828', '#1565c0', '#2e7d32', '#455a64'],
    mechanics: { noHonk: true },
    food: { id: 'sawhchiar', name: 'Sawhchiar', kind: 'heal', amount: 30, time: 4, desc: 'Rice porridge with meat. Heals 30 HP.' },
    zoneMsgs: ['Zone a lo kal ta, tlan rawh!', 'The zone is coming — run!'],
    killVerbs: ['queued', 'sent downhill', 'lane-disciplined', 'benched'],
    win: 'WINNER WINNER BAI DINNER',
    plane: 'Zoram Air MZ-01',
    bots: ['LaneDiscipline', 'NoHonkNinja', 'CherawChamp', 'BaraBazar', 'StiltHouse', 'SecondGearOnly', 'MizoMessi', 'Tlawmngaihna', 'BaiBoss', 'DurtlangDrifter', 'ZoFootball', 'AnthuriumAce', 'SawhchiarSniper', 'ChanmariChamp', 'ReiekPeak', 'HonestyShop', 'SundayRest', 'RidgeRunner', 'ZawlbukZ', 'AizawlFC'],
    tips: ['Steep map: sprinting uphill is slow, downhill is fast.', 'Vehicle horns don\'t work here. This is Aizawl.', 'Houses are on stilts — you can hide underneath.', 'Honesty shops have free boosts. Leave money. (There is no money.)'],
  },

  // ------------------------------------------------------------------ NAGALAND
  {
    id: 'nagaland', name: 'Nagaland', native: 'Kohima · Kisama', state: 'Nagaland',
    tagline: 'Land of festivals — and the King Chilli',
    blurb: 'Hornbill Festival morungs, misty Dzukou valley, a solemn war memorial and a chilli that fights back.',
    sky: 'kloofendal_overcast_puresky', exposure: 1.05, env: 1.0, sun: 1.6, fog: 0.0030, fogColor: '#aeb6b4',
    weather: {},
    terrain: { kind: 'hills', amp: 75, freq: 1 / 360, base: 35 },
    ground: ['grass', 'mudLeaves', 'mossyRock', 'grassSparse'],
    rivers: [{ pts: [[-520, 420], [-200, 380], [100, 440], [520, 400]], w: 26 }],
    roads: [
      { pts: [[-500, -100], [-200, -60], [0, -80], [200, -20], [500, -60]], w: 10 },
      { pts: [[0, -80], [-30, -500]], w: 9 },
      { pts: [[-200, -60], [-260, 200], [-330, 330]], w: 9 },
      { pts: [[200, -20], [260, 250]], w: 8 },
    ],
    districts: [
      { x: 0, z: -140, w: 300, d: 140, style: 'hill', block: 38 },
      { x: -40, z: -330, w: 220, d: 150, style: 'hill', block: 40 },
      { x: 320, z: -200, w: 200, d: 180, style: 'village', block: 46 },
      { x: 300, z: 100, w: 180, d: 150, style: 'village', block: 46 },
    ],
    landmarks: [
      { kind: 'morungs', x: -300, z: 250, egg: E('hornbill', 'Hornbill Festival Grounds', 'The "Festival of Festivals". Every tribe, one stage, and the best rock contest in the Northeast.', 45) },
      { kind: 'cemetery', x: 100, z: -40, egg: E('kohima', 'War Cemetery', '"When you go home, tell them of us..." A moment of silence here. No looting on the terraces.', 35) },
      { kind: 'church', x: -150, z: -220, color: '#f0ede6', spires: 1, tall: true, egg: E('kcathedral', 'The Cathedral on the Hill', 'One of the largest churches in the region, looking over the whole ridge.', 25) },
      { kind: 'hornbill_statue', x: -220, z: 200, egg: E('hornbillbird', 'Great Hornbill', 'The bird, the festival, the legend. The casque on its beak is the real helmet Lv.3.', 15) },
    ],
    props: [
      { kind: 'chilli_stall', x: -40, z: -60, egg: E('rajamircha', 'Raja Mircha', '1,000,000 Scoville. +100 boost, -100 dignity. Your screen will literally burn.') },
      { kind: 'log_drum', x: -350, z: 230, egg: E('logdrum', 'Log Drum', 'Loud enough to call your whole squad from the next valley.') },
      { kind: 'stall', x: 60, z: -170, rot: 0, sign: ['SMOKED PORK', 'with bamboo shoot'], color: '#6d4c41', egg: E('smokedpork', 'Smoked Pork', 'Smoked pork with fermented bamboo shoot. The aroma alone heals 10 HP.') },
      { kind: 'sign', x: 260, z: 380, rot: 0, text: ['DZUKOU VALLEY', 'Bring a jacket · leave your worries'], egg: E('dzukou', 'Dzukou Valley', 'Rolling green hills and lilies. The most peaceful place to get third-partied.') },
      { kind: 'banner', x: -250, z: 280, rot: 0, text: ['HORNBILL ROCK CONTEST', 'Loudest place in the Northeast'], egg: E('rock', 'Rock Contest', 'The bands here will make your ears ring louder than an AWM.') },
      { kind: 'sign', x: 0, z: 30, rot: 2, text: ['NH-29', 'Potholes with their own ecosystem'], egg: E('nh29', 'NH-29', 'Some of these potholes have fish. Some have frogs. One has a family of ducks.') },
      { kind: 'lights', x: 20, z: -140, egg: E('christmas', 'Christmas Lights', 'Christmas here turns the whole state into a light show. Stars on every house.', 30) },
    ],
    trees: { kinds: ['pine', 'raintree', 'bamboo', 'pine'], count: 2000 },
    vehicles: ['jeep', 'jeep', 'bike', 'bike'], vehicleCount: 11,
    signs: ['NAGA SHAWLS', 'HORNBILL CAFE', 'SMOKED PORK HOUSE', 'KOHIMA BAKERY', 'MUSIC STORE', 'TEA STALL', 'BAMBOO CRAFTS', 'AXONE KITCHEN', 'MOBILE HUB'],
    neon: ['#ff3f8e', '#2de2e6', '#ffb000'],
    walls: ['#e0e0e0', '#c5e1a5', '#90caf9', '#ffcc80', '#ef9a9a', '#b0bec5'],
    roofs: ['#b71c1c', '#1565c0', '#37474f', '#2e7d32'],
    mechanics: { kingChilli: true },
    food: { id: 'rajamircha', name: 'Raja Mircha', kind: 'boost', amount: 100, time: 2, desc: 'King chilli. +100 boost. Burns. A lot.', burn: true },
    zoneMsgs: ['Zone ahise, dorai jabi!', 'The zone is coming, run away!'],
    killVerbs: ['chillied', 'drummed', 'morung-ed', 'hornbilled'],
    win: 'WINNER WINNER SMOKED PORK DINNER',
    plane: 'Hornbill Air NL-07',
    bots: ['RajaMircha', 'HornbillHero', 'LogDrummer', 'DzukouDreamer', 'KohimaKid', 'MorungMonk', 'SmokedPorkSniper', 'AxoneAce', 'KisamaKing', 'NH29Navigator', 'BambooShoot', 'RockContest', 'ShawlShooter', 'ChristmasStar', 'MistyRidge', 'JapfuPeak', 'KingChilliKing', 'FestivalOfFestivals', 'TribeSquad', 'NagaNinja'],
    tips: ['Raja Mircha: +100 boost instantly, but your screen shakes for a while.', 'The festival grounds have lots of loot in the morungs.', 'Misty hills — use the fog to reposition.', 'The cemetery terraces are a no-loot zone. Be respectful.'],
  },

  // ------------------------------------------------------------------ SPITI
  {
    id: 'spiti', name: 'Spiti Valley', native: 'स्पीति', state: 'Himachal Pradesh',
    tagline: 'Oxygen 60%. Views 100%.',
    blurb: 'Cold desert at 4,000 m. Monasteries on cliffs, the highest post office in the world and Maggi that tastes like victory.',
    sky: 'kloofendal_43d_clear_puresky', exposure: 0.72, env: 0.8, sun: 3.0, fog: 0.0008,
    weather: { snow: 0.35 },
    terrain: { kind: 'valley', amp: 190, freq: 1 / 300, base: 20 },
    rivers: [{ pts: [[-520, 60], [-250, 20], [0, 80], [250, 40], [520, 100]], w: 30 }],
    lakes: [{ x: -320, z: -330, r: 60, lake: true, crescent: true }],
    ground: ['gravel', 'dryGround', 'rockTerrain', 'snow'],
    snowLine: 150,
    roads: [
      { pts: [[-500, 120], [-250, 110], [0, 140], [250, 100], [500, 150]], w: 9 },
      { pts: [[0, 140], [60, 0], [40, -120], [-150, -120]], w: 7 },
      { pts: [[250, 100], [270, -180], [330, -300]], w: 7 },
    ],
    districts: [
      { x: 60, z: 200, w: 200, d: 100, style: 'spiti', block: 34 },
      { x: -250, z: 180, w: 140, d: 80, style: 'spiti', block: 34 },
      { x: 300, z: 200, w: 140, d: 90, style: 'spiti', block: 34 },
      { x: 280, z: -250, w: 120, d: 90, style: 'spiti', block: 34 },
    ],
    landmarks: [
      { kind: 'monastery', x: -150, z: -150, egg: E('keygompa', 'The Monastery on the Cone', '1000 years of calm on a hilltop. Please don\'t shoot here. ...Fine. But quietly.', 40) },
      { kind: 'buddha', x: 250, z: -330, egg: E('langza', 'The Great Buddha', 'Watching over the valley. And over your terrible aim.', 25) },
      { kind: 'high_bridge', x: -240, z: 45, rot: 1, egg: E('chicham', 'The High Bridge', 'One of Asia\'s highest bridges. Don\'t look down. Actually — look down.', 30) },
      { kind: 'post_office', x: 330, z: -170, egg: E('hikkim', 'World\'s Highest Post Office', 'Send a postcard from 4,400 m. It arrives next monsoon. Worth it.', 15) },
    ],
    props: [
      { kind: 'stall', x: 20, z: 160, rot: 2, sign: ['MAGGI POINT', '2 min to cook · 20 min to cool'], color: '#ffd600', egg: E('maggi', 'Maggi Point', 'Maggi at 4,000 m tastes like victory. The recipe is the same. The altitude is the secret ingredient.') },
      { kind: 'bikers', x: -80, z: 130, egg: E('bikers', 'Biker Gang', '"Bro, life-changing trip." Every single one of them. They\'re right though.') },
      { kind: 'sign', x: 100, z: 120, rot: 2, text: ['OXYGEN 60%', 'Sprint responsibly'], egg: E('thinair', 'Thin Air', 'Stamina drains faster up here. Your lungs are doing their best.') },
      { kind: 'snow_leopard', x: 150, z: -350, egg: E('leopard', 'Snow Leopard', 'A snow leopard was spotted. It saw you. It did not care.', 20) },
      { kind: 'yaks', x: -120, z: 250, n: 5, egg: E('yaks', 'Yak Traffic', 'Yak traffic jam. Honking does not work on yaks. Nothing works on yaks.') },
      { kind: 'sign', x: -380, z: 130, rot: 1, text: ['NO NETWORK ZONE', 'Your story will upload in Manali'], egg: E('network', 'No Network', 'Zero bars. Your Instagram story will upload three days later in Manali.') },
      { kind: 'flags', x: -150, z: -80, egg: E('flags', 'Prayer Flags', 'Every flutter carries a prayer on the wind. Maybe one for your squad.', 15) },
      { kind: 'flags', x: 250, z: -290 }, { kind: 'flags', x: -230, z: 60 }, { kind: 'flags', x: 60, z: 230 },
    ],
    trees: { kinds: ['poplar', 'willow', 'poplar'], count: 380 },
    vehicles: ['bike', 'bike', 'bike', 'jeep'], vehicleCount: 11,
    signs: ['HOMESTAY', 'MAGGI POINT', 'CAFE 4000', 'MONK CAFE', 'BIKE REPAIR', 'THUKPA HOUSE', 'KAZA STORES', 'YAK CHEESE', 'SEA BUCKTHORN TEA'],
    neon: ['#2de2e6', '#ffb000', '#ff3f8e'],
    walls: ['#f4f1ea', '#efe9dc', '#ece5d4'],
    roofs: ['#6d4c41'],
    mechanics: { thinAir: true, cold: true },
    food: { id: 'maggi', name: 'Maggi', kind: 'heal', amount: 30, time: 4, desc: 'Maggi at altitude. Heals 30 HP.' },
    zoneMsgs: ['Zone aa rahi hai, jaldi chalo!', 'The zone is coming — move fast!'],
    killVerbs: ['sent downhill', 'altitude-sicked', 'yak-ed', 'frozen'],
    win: 'WINNER WINNER MAGGI DINNER',
    plane: 'Himalayan Air HP-41',
    bots: ['MaggiPoint', 'KeyGompa', 'ChandratalChill', 'BulletRider', 'LifeChangingTrip', 'OxygenLow', 'YakJam', 'HikkimPostman', 'LangzaLooker', 'KazaKid', 'SnowLeopard', 'ThukpaThunder', 'PinValley', 'KunzumPass', 'SeaBuckthorn', 'NoNetwork', 'ChichamChamp', 'CliffMonk', 'PrayerFlag', 'ColdDesert'],
    tips: ['Thin air: sprinting drains stamina faster. Pace yourself.', 'Snow on the peaks — you leave a silhouette against it.', 'The monastery hill gives a 360° view of the valley.', 'Maggi heals 30. Best consumed hot.'],
  },
];

export const MAP_BY_ID = Object.fromEntries(MAPS.map((m) => [m.id, m]));
