# Rebuilds the '90% SCALE' block at the end of dp-schedule-planner.html's stylesheet:
# a scoped copy of every length rule inside .panes, x$Z and rounded to whole pixels,
# plus the parity fixes. Run after editing any size in the planner's CSS:
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\z90.ps1
param([double]$Z = 0.9)
$p='C:\Users\asus\Documents\dispatch pro\Claude\dp-schedule-planner.html'
$enc=New-Object System.Text.UTF8Encoding($false)
$s=[IO.File]::ReadAllText($p,$enc)
$START='/* ==== 90% SCALE - generated by tools/z90.ps1; do not hand-edit ==== */'
$END='/* ==== end 90% SCALE ==== */'
$a=$s.IndexOf('<style>')+7; $b=$s.IndexOf('</style>',$a)
$css=$s.Substring($a,$b-$a)
# drop any previous generated block
# every earlier generated block, whatever its marker's dash was encoded as
$css=[regex]::Replace($css,'\s*/\* ==== 90% SCALE[\s\S]*?/\* ==== end 90% SCALE ==== \*/\s*',"`n")
$src=[regex]::Replace($css,'/\*[\s\S]*?\*/','')

function ScaleVal([string]$v){
  return [regex]::Replace($v,'(-?\d*\.?\d+)px',{ param($m)
    $n=[double]$m.Groups[1].Value
    if([math]::Abs($n) -le 1.5){ return $m.Value }
    $r=[math]::Round($n*$Z,[MidpointRounding]::AwayFromZero)
    return ([string]$r)+'px' })
}
$LEN='^(--.*|font-size|line-height|width|height|min-width|min-height|max-width|max-height|padding.*|margin.*|gap|row-gap|column-gap|top|left|right|bottom|inset|flex|flex-basis|border|border-top|border-right|border-bottom|border-left|border-width|border-radius|border-.*-radius|outline.*|box-shadow|transform|letter-spacing|text-underline-offset|background-size|background-position|grid-template-columns|grid-template-rows|-webkit-mask|mask)$'

function SplitTop([string]$t,[char]$sep){
  $out=New-Object System.Collections.Generic.List[string]; $d=0; $cur=''
  foreach($ch in $t.ToCharArray()){
    if($ch -eq '('){$d++} elseif($ch -eq ')'){$d--}
    if($ch -eq $sep -and $d -eq 0){ $out.Add($cur); $cur='' } else { $cur+=$ch } }
  if($cur.Trim()){ $out.Add($cur) }
  return ,$out
}
function ScopeSel([string]$sel){
  $sel=$sel.Trim()
  if($sel -eq 'body'){ return '.panes' }
  if($sel -match '\.panes'){ return $sel }
  if($sel -match '^(html|:root)$'){ return $null }
  # a leading :root[...] / body.x / html compound stays outermost
  $m=[regex]::Match($sel,'^((?::root|html|body)[^\s>+~]*)\s*(.*)$')
  if($m.Success -and $m.Groups[1].Value -ne ''){
    if($m.Groups[2].Value -eq ''){ return $null }
    return $m.Groups[1].Value+' .panes '+$m.Groups[2].Value }
  return '.panes '+$sel
}
$sb=New-Object System.Text.StringBuilder
function Walk([string]$t,[string]$indent){
  $i=0; $n=$t.Length
  while($i -lt $n){
    $o=$t.IndexOf('{',$i); if($o -lt 0){break}
    $pre=$t.Substring($i,$o-$i).Trim()
    # find the matching close brace
    $d=0; $j=$o
    for(;$j -lt $n;$j++){ if($t[$j] -eq '{'){$d++} elseif($t[$j] -eq '}'){$d--; if($d -eq 0){break}} }
    $body=$t.Substring($o+1,$j-$o-1); $i=$j+1
    if($pre.StartsWith('@')){
      if($pre -match '^@media' -and $pre -notmatch 'prefers-reduced-motion'){
        $inner=New-Object System.Text.StringBuilder
        $script:sbStack=$sb; $save=$script:sb; $script:sb=$inner
        Walk $body '  '
        $script:sb=$save
        if($inner.Length){ [void]$sb.Append($pre+'{'+"`n"+$inner.ToString()+'}'+"`n") } }
      continue }
    $decls=SplitTop $body ';'
    $keep=@()
    foreach($dl in $decls){ $k=$dl.IndexOf(':'); if($k -lt 0){continue}
      $prop=$dl.Substring(0,$k).Trim(); $val=$dl.Substring($k+1).Trim()
      if($prop -notmatch $LEN){continue}
      if($prop.StartsWith('--') -and $val -notmatch '\d+(\.\d+)?px'){continue}
      $keep+=($prop+':'+(ScaleVal $val)) }
    if(-not $keep.Count){continue}
    $parts=SplitTop $pre ','
    # html,body{height:100%} is the page's, not the section's
    if(($parts | % { $_.Trim() }) -contains 'html'){ continue }
    $sels=@(); foreach($x in $parts){ $y=ScopeSel $x; if($y){$sels+=$y} }
    if($pre -match '^\s*:root(\[data-theme="light"\])?\s*$'){
      # the token blocks: only the px ones, onto the section itself
      $sels=@( $(if($pre -match 'light'){':root[data-theme="light"] .panes'}else{'.panes'}) ) }
    if(-not $sels.Count){continue}
    [void]$sb.Append($indent+($sels -join ',')+'{'+($keep -join ';')+'}'+"`n")
  }
}
# icons are sized by their width/height ATTRIBUTES, which no CSS copy touches:
# give each attribute size its 90% whole-pixel size inside the section. First,
# so any component rule that sizes its own icon still wins.
foreach($px in 8..28){ $r=[math]::Round($px*$Z,[MidpointRounding]::AwayFromZero)
  if($r -ne $px){ [void]$sb.Append('.panes svg[width="'+$px+'"]{width:'+$r+'px;height:'+$r+'px}'+"`n") } }
Walk $src ''
# PARITY: x0.9 turns some even boxes odd (46->41, 28->25, 30->27, 26->23), and a
# line box centred in an odd box lands on a half pixel — soft text. These put
# each such box back on an even height. Keep in step with the script's zp()
# callers (bh 26 collapsed, the 22px add button, the 14px bubble).
$FIX=@'
/* parity: even boxes for everything that centres text */
.panes{--bar-h:26px;--head-h:42px}
.panes .nmline{height:16px}
.panes .gname{line-height:16px}
.panes .lg{height:26px}
.panes .kpi,.panes .orow{min-height:30px}
.panes .kpi .d{line-height:14px}
.panes .pnhead{height:42px}
.panes .ptabs{height:28px}
.panes .inp,.panes select.sel,.panes button.sel,.panes .trig,.panes .btn{height:28px}
.panes .btn.ic{width:28px}
.panes select.sel.sm,.panes button.sel.sm,.panes .trig.sm,.panes .btn.sm,.panes .inp.sm,
.panes .search-box,.panes .cal-tools .search-box,.panes .rp-tools .search-box{height:24px}
.panes .btn.sm.ic{width:24px}
.panes .step{height:24px}
.panes .step button{width:22px;height:22px}
.panes .step .today{width:auto}
.panes .ptabs .cnt{line-height:14px}
.panes .wl-row,.panes .exc{min-height:42px}
.panes .wl-row .d,.panes .exc .d{line-height:14px}
.panes .gbadge{line-height:12px}
.panes .bd-state .lab{line-height:14px}
'@
[void]$sb.Append($FIX+"`n")
$gen="`n"+$START+"`n/* The board section (.panes: the tabbed panel, the board, the details pane,`n   the track page) at 90%, built as REAL whole-pixel sizes rather than`n   zoom:0.9, which would paint 11px text at 9.9px and soften every glyph.`n   Every length inside the section is x0.9, rounded; 1-1.5px hairlines stay.`n   The header, the sidebar and the overlays (dialogs, menus, toasts, hover`n   card) keep their sizes. Re-run z90.ps1 after editing any size above. */`n"+$sb.ToString()+$END+"`n"
$css=$css.TrimEnd()+"`n"+$gen
$s=$s.Substring(0,$a)+$css+$s.Substring($b)
[IO.File]::WriteAllText($p,$s,$enc)
"generated rules: "+([regex]::Matches($sb.ToString(),'\{')).Count
